---
- name: install initial packages on all boxes
  hosts: all 
  remote_user: ansible
  become: true
  become_method: sudo
  tasks:
  - name: install all initial packages
    yum:
      name: ['man', 'epel-release', 'man-pages', 'mlocate','chrony', 'vim', 'sysstat', 'bind-utils']
      state: latest
