---
- name: Install Kubernetes and Docker
  hosts: [kubew, kubem]
  remote_user: ansible
  become: yes 

  vars: 
    kubernetes_allow_pods_on_master: true
  
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
