---
- hosts: nagios
  become: yes

  tasks:
  - name: install these packages
    shell: yum install -y gcc glibc glibc-common gd gd-devel make net-snmp openssl-devel httpd php unzip wget postfix perl


  - name: start http and enable
    service: name=httpd state=started enabled=yes

  - name: add group nagcmd
    group:
      name: nagcmd

  - name: add the user nagios
    user:
      name: nagios
      password: $1$LY1nvQG9$0AT9KOD7aHA1Bxf4wqp2m/
      state: present

  - name: add apache user to nagcmd group
    user:
      name: apache
      group: nagcmd
      append: yes

  - name: add nagios user to nagcmd group
    user:
      name: nagios
      group: nagcmd
      append: yes


  - name: dowwnload nagios
    shell: wget -O nagioscore.tar.gz https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.5.tar.gz

  - name: extract the nagios archive
    shell: tar xvf nagios*.tar.gz

  - name: change into the dir and execute this command
    command: ./configure --with-command-group=nagcmd
    args:
      chdir: /home/ansible/nagioscore-nagios-4.4.5

  - name: run the make all command
    shell: make all
    args:
      chdir: /home/ansible/nagioscore-nagios-4.4.5

  - name: run make install
    shell: make install
    args:
      chdir: /home/ansible/nagioscore-nagios-4.4.5

  - name: run make install commandmode
    shell: make install-commandmode
    args:
      chdir: /home/ansible/nagioscore-nagios-4.4.5

  - name: run make install-init
    shell: make install-init
    args:
      chdir: /home/ansible/nagioscore-nagios-4.4.5

  - name: run make install-config
    shell: make install-config
    args:
      chdir: /home/ansible/nagioscore-nagios-4.4.5

  - name: run install-webconf
    shell: make install-webconf
    args:
      chdir: /home/ansible/nagioscore-nagios-4.4.5

  - name: download nagios-plugin
    shell: wget http://nagios-plugins.org/download/nagios-plugins-2.3.2.tar.gz
    args:
      chdir: ~


  - name: extract plugin
    shell: tar xzvf nagios-plugins-*.tar.gz


  - name: change into nagios plugin and run commands
    command: ./configure --with-nagios-user=nagios --with-nagios-group=nagios --with-openssl
    args:
      chdir: /home/ansible/nagios-plugins-2.3.2

  - name: run make
    command: make
    args:
      chdir: /home/ansible/nagios-plugins-2.3.2
  - name: run make all
    command: make all
    args:
      chdir: /home/ansible/nagios-plugins-2.3.2
  - name: change dir
    shell: cd ~

  - name: comment out a line in this file
    template:
      src: /ansible/nagios/servers.j2
      dest: /usr/local/nagios/etc/nagios.cfg

  - name: make directory
    file:
      path: /usr/local/nagios/etc/servers
      state: directory

  - name: configure email address in contacts.cfg
    template:
      src: /ansible/nagios/contacts.j2
      dest: /usr/local/nagios/etc/objects/contacts.cfg

  - name: restart httpd
    service:
      name: httpd
      state: restarted
      enabled: yes

  - name: config check
    shell: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg

  - name: start nagios
    service:
      name: nagios
      state: started
      enabled: yes

