---
<<<<<<< HEAD
- hosts: centos7
=======
- hosts: all
  remote_user: ansible
>>>>>>> 9b42cee7115f9fced3ea09b9abafc0a931497cd5
  become: yes
  vars:
    - ansible_password: 'password'
  gather_facts: no
  tasks:
<<<<<<< HEAD
    - name: Disable Root Login
      lineinfile:
          dest=/etc/ssh/sshd_config
          regexp='^PermitRootLogin'
          line="PermitRootLogin no"
          state=present
          backup=yes
      notify: Restart SSHD
  
    - name: selinux disable
      shell: |
         setenforce 0
         sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
     
    - name: firewall disable
      shell: systemctl stop firewalld

  handlers:
      - name: Restart SSHD
        service:
          name: sshd
          state: restarted
=======


   - name: Disable Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
     notify: restart ssh
  

   - name: selinux off
     shell: setenforce 0
     shell: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
     
   - name: firewall off
     service:
        name:
         - firewalld
         - iptables
        state: stopped
        enabled: no
     ignore_errors: yes


  handlers:
     - name: restart ssh
       service:
         name=sshd
         state=restarted
>>>>>>> 9b42cee7115f9fced3ea09b9abafc0a931497cd5
