---
- hosts: centos6
  remote_user: ansible
  become: yes
  vars:
    - ansible_password: 'password'
  gather_facts: no
  tasks:
    - name: Disable Root Login
      lineinfile:
          dest=/etc/ssh/sshd_config
          regexp='^PermitRootLogin'
          line="PermitRootLogin no"
          state=present
          backup=yes
      notify: Restart SSHD
  
    - name: selinux disable
      shell: |
         setenforce 0
         sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
     
    - name: firewall stop
      shell: service iptables stop

  handlers:
      - name: Restart SSHD
        service:
          name: sshd
          state: restarted
