---
- name: use mail role playbook
  hosts: mail 
  user: ansible
  become: true

  pre_tasks:
    - debug:
        msg: 'Beginning web server configuration.'

  roles:
    - mail 

  post_tasks:
    - debug:
        msg: 'Web server has been configured.'
