---
# tasks file for php-stack
- name: Install php packages
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-gd
    - php-mysql
    - php-mbstring
    - php-process
    - php-xmlrpc
    - php-xml
    - libxslt
    - php-mcrypt
